"""Agrega score y descripcion a Post

Revision ID: 902351149b55
Revises: 14f279bfe805
Create Date: 2025-09-05 21:15:26.862373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902351149b55'
down_revision = '14f279bfe805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solucionado', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('solucionado')

    # ### end Alembic commands ###
